config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'cocktails#index'

  post '/cocktails/random', to: 'cocktails#random', as: :random_cocktail
  get '/cocktails/random', to: 'cocktails#random' # fallback

  post '/cocktails/search', to: 'cocktails#search', as: :search_cocktail

  resources :cocktails do
    resources :doses #, only: [:create, :update, :destroy ]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  def self.search(unsafe_prop, user_search_string)
    self.where("#{unsafe_prop} ~* :re", re: "\\y#{Regexp.escape(user_search_string)}\\y")
    # e.g. Cocktail.search(:name, 'ace')
  end
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy

  has_many :ingredients, through: :doses

  validates :name, presence: true, uniqueness: true

  mount_uploader :photo, PhotoUploader
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :cocktail, presence: true
  validates :ingredient, presence: true
  # validates :qty, presence: true
  # validates :qty_unit, presence: true
  validates :qty_raw, presence: true
  # validates_inclusion_of :qty_unit, in: %w[unit ml cl g oz]
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses, dependent: :restrict_with_error
  has_many :cocktails, through: :doses
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    per_page = 12
    @page_idx = params[:page] ? params[:page].to_i - 1 : 0
    @page_human = @page_idx + 1

    results = params[:q] ? Cocktail.search(:name, params[:q]) : Cocktail.all

    @cocktails = results.order(:name).limit(per_page).offset(per_page * @page_idx)
    @max_page_idx = ((results.count - 1).to_f / per_page).floor
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new # keeps user input to avoid writing everything again when error
    end
  end

  def edit
    @cocktail = Cocktail.find(params[:id])
  end

  def update
    @cocktail = Cocktail.find(params[:id])
    if @cocktail.update(cocktail_params)
      redirect_to cocktail_path(@cocktail)
    else
      render :new # keeps user input to avoid writing everything again when error
    end
  end

  def destroy
    @cocktail = Cocktail.find(params[:id])
    dose_ids = @cocktail.doses.ids
    dose_ids.each do |id|
      @dose = Dose.find(id)
      @dose.destroy
    end

    @cocktail.destroy
    redirect_to cocktails_path
  end

  def search
    redirect_to cocktails_path(q: params[:q])
  end

  def random
    offset = rand(Cocktail.count)
    @cocktail = Cocktail.offset(offset).first
    redirect_to cocktail_path(@cocktail)
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :description, :photo, :photo_cache, :pic)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    ingredient = Ingredient.find(params[:dose][:ingredient_id])

    pars = dose_params
    pars[:cocktail] = @cocktail

    Dose.create!(pars)
    # TODO: implement correct logic for validation/permission error handling

    redirect_to cocktail_path(@cocktail)
  end

  def edit
    @dose = Dose.find(params[:id])
  end

  def update
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.find(params[:id])

    @dose.update(dose_params)

    redirect_to cocktail_path(@cocktail)
  end

  def destroy
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.find(params[:id])
    # dose_ids = @cocktail.doses.ids
    # dose = Dose.where(cocktail_id: params[:cocktail_id])
    @dose.destroy
    redirect_to cocktail_path(@cocktail)

    # dose_ids.each do |id|
    #   @dose = Dose.find(id)
    #   @dose.destroy
    # end
    # # @dose = Dose.find(params[:id])
    # redirect_to cocktail_path(@cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:ingredient_id, :qty_raw)
  end
end

# cocktail_doses POST   /cocktails/:cocktail_id/doses(.:format)       doses#create
#  cocktail_dose PATCH  /cocktails/:cocktail_id/doses/:id(.:format)   doses#update
#                PUT    /cocktails/:cocktail_id/doses/:id(.:format)   doses#update
#                DELETE /cocktails/:cocktail_id/doses/:id(.:format)   doses#destroy

# Format data is save in a cocktail object
# <Dose id: 234, qty: 99, qty_unit: "ml", cocktail_id: 1, ingredient_id: 3201, created_at: "2018-11-15 11:05:23", updated_at: "2018-11-15 11:05:23", qty_raw: nil>

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/views/application/_navbar.html.erb
<header>
  <div id='logo-bar'>
    <div class='logo-bar-inner'>
      <%= link_to :root, class: "link-nodecorate" do %>
        <div id="logo">
          <div class="logo-shadow"></div>
        </div>
      <% end %>
      <%= link_to :root, class: "link-nodecorate" do %>
        <div class="heading">
          <h1>Mix-a-Lot</h1>
          <p><em>We cannot lie — our cocktail recipes are the best!</em></p>
        </div>
      <% end %>
    </div>
  </div>

  <nav id='top-nav'>
    <ul class="nav nav-tabs nav-list">
      <%
        is_homepage = %i[root cocktails].any? { |el| current_page? el } && (!params[:q] || params[:q].empty?)
      %>

      <%
        tabs = [
          { txt: 'Home', icon: 'home', path: :root, alt_path: :cocktails, active: is_homepage },
          { txt: 'Create', icon: 'plus', path: :new_cocktail, active: current_page?(:new_cocktail) },
          { txt: 'Random', path: :random_cocktail, method: :post, active: false }
        ]
      %>

      <% tabs.each do |tab| %>

        <%
          classes = []
          classes << 'active' if tab[:active]
          classes += (tab[:classes] || [])
        %>

        <li role="presentation" class="<%= classes.join(' ') %>">
          <%= link_to tab[:txt], tab[:path], method: tab[:method] || :get, class: 'hidden-xs' %>
          <% if tab[:icon] %>
            <%= link_to tab[:path], class: 'visible-xs' do %>
              <%= fa_icon tab[:icon] %>
            <% end %>
          <% end %>
        </li>


      <% end %>

      <li role="presentation" class='search-outer'>
        <%= render 'search_form' %>
      </li>
    </ul>
  </nav>
</header>

app/views/application/_search_form.html.erb
<%= form_tag(:search_cocktail, class: 'search-form', method: :post) do %>
  <%= text_field_tag :q, params[:q] || '', placeholder: "Search cocktails", class: "" %>
  <%= submit_tag "Go", class: "" %>
<% end %>

app/views/cocktails/_cocktail_img.html.erb
<% if cocktail[:photo] #cloudinary %>
  <%= cl_image_tag cocktail.photo, alt: cocktail.name, height: 700, width: 700, crop: :fill %>
<% elsif cocktail.pic #external url %>
  <%= image_tag cocktail.pic, alt: cocktail.name, height: 700, width: 700, crop: :fill %>
<% else %>
  <%= image_tag("no_img_placeholder.png", alt: "", height: 700, width: 700, crop: :fill) %>
<% end %>

app/views/cocktails/_form.html.erb
<%= simple_form_for(cocktail) do |f| %>
  <%= f.label :name %>
  <br>
  <%= f.text_field :name %>
  <br>
  <br>
  <%= f.label :description, 'Preparation' %>
  <br>
  <%= f.text_area :description %>
  <br>
  <br>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>  <br>
  <br>
  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/cocktails/edit.html.erb
<h2>Editing <%= @cocktail.name %></h2>

<%= render 'form', cocktail: @cocktail%>

app/views/cocktails/index.html.erb
<h2>Cocktails</h2>

<p id="notice"><%= notice %></p>

<% if @cocktails.empty? %>
  <p class="no-results-msg">No results found.</p>
<% else %>
  <div class='row'>

    <% @cocktails.each do |cocktail| %>

        <% desc = cocktail.description || '' %>
        <% desc_truncate_length = 70 %>
        <% desc_truncated = desc.length > desc_truncate_length ? desc[0...desc_truncate_length] + '…' : nil %>

        <div class="col-sm-6 col-md-4 th-parent">

          <%= link_to cocktail_path(cocktail), class: 'th-link' do %>
            <div class="thumbnail homepage-thumb">
              <%= render 'cocktail_img', cocktail: cocktail %>
              <div class="caption">
                <h3><%= cocktail.name %></h3>

                <% if desc_truncated.nil? %>
                  <p><%= cocktail.description %></p>
                <% else %>
                  <p title='<%= cocktail.description %>'>
                    <%= desc_truncated %>
                  </p>
                <% end %>
              </div>
            </div>
          <% end %>
        </div>

    <% end %>

  </div>

  <br>

  <% pgs_below_above = 2 %>

  <% min = @page_idx - pgs_below_above %>
  <% max = @page_idx + pgs_below_above %>

  <% rng = (min..max) %>

  <% if min < 0 %>
    <% min = 0 %>
    <% max = [min + (pgs_below_above) * 2, @max_page_idx].min %>
  <% elsif max > @max_page_idx %>
    <% max = @max_page_idx %>
    <% min = [max - (pgs_below_above) * 2, 0].max %>
  <% end %>

  <% rng = min..max %>

  <% prev_exists = @page_idx > 0 %>
  <% next_exists = @page_idx <= @max_page_idx - 1 %>

  <nav aria-label="pagination">
    <ul class="pagination">

      <li class='<%= prev_exists ? '' : 'disabled'  %>'>
        <%= link_to '«', cocktails_path(page: 1), class: 'page-link' %>
      </li>

      <% rng.each do |n| %>
        <li class='<%= n == @page_idx ? 'active' : ''  %>'>
          <%= link_to "#{n + 1}", cocktails_path(page: n + 1), class: 'page-link' %>
        </li>
      <% end %>

      <li class='<%= next_exists ? '' : 'disabled'  %>'>
        <%= link_to '»', cocktails_path(page: @max_page_idx + 1), class: 'page-link' %>
      </li>


    </ul>
  </nav>
<% end %>

app/views/cocktails/new.html.erb
<h2>Creating New Cocktail</h2>

<%= render 'form', cocktail: @cocktail%>

app/views/cocktails/show.html.erb
<h2><%= @cocktail.name %></h2>

<div class='row'>
  <div class="col-xs-12 col-sm-6 col-md-4">

    <div class="thumbnail">
      <%= render 'cocktail_img', cocktail: @cocktail %>
    </div>

  </div>

  <div class="col-xs-12 col-sm-6 col-md-8">

    <h3>Ingredients</h3>

    <p>
      <ul>
        <% @cocktail.doses.each do |dose|%>
          <li>
            <%= Ingredient.find(dose.ingredient_id).name %>
            (<%= dose.qty_raw.nil? ? "#{dose.qty} #{dose.qty_unit}" : dose.qty_raw.strip %>)

            <%= link_to edit_cocktail_dose_path(@cocktail, dose), class: 'edit' do %>
              <%= fa_icon "pencil", class: 'ib-icon' %>
            <% end %>

            <%= link_to cocktail_dose_path(@cocktail, dose), method: :delete, data: { confirm: "Are you sure you want to delete #{dose.ingredient.name} from #{@cocktail.name}?" }, class: 'delete' do %>
              <%= fa_icon "trash", class: 'ib-icon' %>
            <% end %>

          </li>
        <% end %>
      </ul>
      <%= link_to "Add ingredient", new_cocktail_dose_path(@cocktail), class: "btn" %>
    </p>

    <hr>

    <% if @cocktail.description %>
      <h3>Preparation</h3>

      <% steps = @cocktail.description
        .split(/\d[.)]/)
        .reject { |el| el.empty? }
        .map { |el| el.strip } %>

      <p>
        <% if steps.length < 2 || @cocktail.description.nil? %>
          <%= @cocktail.description %>
        <% else %>
          <ol>
            <% steps.each do |step| %>
              <li><%= step %></li>
            <% end %>
          </ol>
        <% end %>
      </p>
    <% end %>

    <%= link_to 'Edit', edit_cocktail_path(@cocktail), class: 'btn btn-primary' %>
    <%= link_to 'Delete', cocktail_path(@cocktail.id), method: :delete, data: { confirm: "Are you sure you want to delete #{@cocktail.name}?" }, class: 'btn btn-danger' %>


  </div>

  <div class="col-xs-12" style='margin-top: 25px'>
    <%= link_to "Back to cocktails", cocktails_path, class: "btn btn-primary" %>
  </div>

</div>

app/views/doses/_form.html.erb
<%= simple_form_for([@cocktail, dose]) do |f| %>
  <%= f.association :ingredient %>
  <br>
  <br>
  <%= f.label :qty_raw, 'Quantity' %>
  <br>
  <%= f.text_field :qty_raw %>
  <br>
  <br>
  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/doses/edit.html.erb
<% @cocktail = @dose.cocktail %>

<h2>Editing ingredient for <%= @cocktail.name %></h2>

<%= render 'form', dose: @dose%>

app/views/doses/new.html.erb
<h2>Adding ingredient to <%= @cocktail.name %></h2>

<%= render 'form', dose: @dose%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <head>
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta charset="UTF-8">
    </head>
    <title>Mix-a-Lot</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= favicon_link_tag asset_path('favicon.png'), :rel => 'icon', :type =>  'image/png' %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <%= render 'navbar' %>

  <body style='margin: 0px 0 50px 0'>
    <main class='wrapper'>

      <div class='container'>
        <%= yield %>
      </div>

    </main>

    <footer></footer>
  </body>
</html>